#!/bin/bash
set -e
cd `dirname $0`
echo "// file automatically generated by `basename $0`." > fontname.h
echo "#ifndef FONTNAME_H" >> fontname.h
echo "#define FONTNAME_H" >> fontname.h
echo "extern char * fontname[];" >> fontname.h
echo "extern int fontcount;" >> fontname.h
echo "#endif" >> fontname.h

echo "// file automatically generated by `basename $0`." > fontname.c
echo "#include \"fontname.h\"" >> fontname.c
echo "#include <stdlib.h>" >> fontname.c
v=`convert -list font  | grep Font: | grep -vi emoji| wc -l`
v=$[v+2]
echo "int fontcount=$v;" >> fontname.c
echo "char * fontname[$v] = { NULL," >> fontname.c
convert -list font  | grep Font: | grep -vi emoji| sed -e s/Font:// | tr -d ' ' | sed -e 's/\(^.*$\)/    \"\1\",/' >> fontname.c

echo "    NULL};" >> fontname.c
